# NumPy Practice


In [30]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [31]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
              [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [32]:
a1

array([1, 2, 3])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [33]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.shape, a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [34]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [35]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.size, a3.dtype, type(a3)

((3, 3), 2, 9, dtype('int32'), numpy.ndarray)

In [36]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
adf1 = pd.DataFrame({"a1": a1})
adf1


a1
0   1
1   2
2   3

In [37]:
# Create an array of shape (10, 2) with only ones
shape = (10,2)
np.ones(shape, dtype= int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [38]:
# Create an array of shape (7, 2, 3) of only zeros
shape = (7, 2, 3)
np.zeros(shape, dtype= int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [39]:
# Create an array within a range of 0 and 100 with step 3
p1 = np.arange(0, 100, 3)
p1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [40]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
p2 = np.random.randint(0,10, size = (7,2))
p2

array([[6, 8],
       [6, 0],
       [0, 8],
       [8, 3],
       [8, 2],
       [6, 5],
       [7, 8]])

In [41]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
# p3 = np.random.uniform(0,1, size = (3,5))
p3 = np.random.rand(3,5)
p3

array([[0.48482997, 0.69243603, 0.26941233, 0.24412552, 0.16829104],
       [0.21876422, 0.558102  , 0.40383617, 0.06489225, 0.25391541],
       [0.24687606, 0.69630427, 0.71227059, 0.14808693, 0.99774049]])

In [42]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
p4 = np.random.randint(0,10, size = (4, 6))
p4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [43]:
#The array is not changed despite using random module.
#  It is due to the seed() function which generates pseudo-random numbers.
#  Here, we have set seed value to 42 and every time the code is executed the same random numbers are generated. 

In [44]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
p5 = np.random.randint(1,10 , size = (3, 7))
p5
# Find the unique numbers in the array you just created
unique_elements = np.unique(p5)
unique_elements

array([1, 2, 3, 4, 5, 7, 9])

In [45]:
# Find the 0'th index of the latest array you created
print(f"0th index = {unique_elements[0]}")

0th index = 1


In [46]:
# Get the first 2 rows of latest array you created
p5[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [47]:
# Get the first 2 values of the first 2 rows of the latest array
#p5.flatten()[:4]
p5[:2, :2]

array([[9, 1],
       [5, 3]])

In [48]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
x1 = np.random.randint(0,10,(3,5))
x2 = np.ones((3,5), dtype= int)
print(f"x1 = \n{x1} \n\nx2 = \n{x2}")

x1 = 
[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]] 

x2 = 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [49]:
# Add the two arrays together
x3 = x1 + x2
x3

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [50]:
# Create another array of ones of shape (5, 3)
x4 = np.ones((5,3))
x4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# Try add the array of ones and the other most recent array together
x3 + x4

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

<!-- => It is because the shape of two arrays are different, here x3 => (3,5) while x4 => (5, 3). So, it produces a broadcasting error.  -->
<!--  It can be fixed by transposing one of the two arrays (only here because one is (3,5) and the other is (5,3)) -->

While trying to add the above two numpy arrays, it produced a ValueError since shapes of the two arrays viz. x3 ad x4 were different ((3,5) and (5,3) resp.) and so they could not be broadcasted together.

In [ ]:
sum = (x3 + x4.T)
sum, sum.shape


(array([[ 4.,  4., 10.,  8.,  6.],
        [11.,  8., 10.,  2.,  8.],
        [ 7., 11., 10.,  2.,  5.]]),
 (3, 5))

In [ ]:
# Create another array of ones of shape (3, 5)
x5 = np.ones((3,5))
x5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract the new array of ones from the other most recent array
diff =  sum - x5
diff

array([[ 3.,  3.,  9.,  7.,  5.],
       [10.,  7.,  9.,  1.,  7.],
       [ 6., 10.,  9.,  1.,  4.]])

In [ ]:
# Multiply the ones array with the latest array
mul = sum * x5
mul

array([[ 4.,  4., 10.,  8.,  6.],
       [11.,  8., 10.,  2.,  8.],
       [ 7., 11., 10.,  2.,  5.]])

In [ ]:
# Take the latest array to the power of 2 using '**'
mul ** 2

array([[ 16.,  16., 100.,  64.,  36.],
       [121.,  64., 100.,   4.,  64.],
       [ 49., 121., 100.,   4.,  25.]])

In [ ]:
# Do the same thing with np.square()
sq = np.square(mul)
sq

array([[ 16.,  16., 100.,  64.,  36.],
       [121.,  64., 100.,   4.,  64.],
       [ 49., 121., 100.,   4.,  25.]])

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(sq)

58.93333333333333

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(sq)

121.0

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(sq)

4.0

In [ ]:
# Find the standard deviation of the latest array
np.std(sq)

40.28145423834094

In [ ]:
# Find the variance of the latest array
np.var(sq)

1622.5955555555554

In [ ]:
# Reshape the latest array to (3, 5, 1)
sq1 = sq.reshape(3, 5, 1)
sq1

array([[[ 16.],
        [ 16.],
        [100.],
        [ 64.],
        [ 36.]],

       [[121.],
        [ 64.],
        [100.],
        [  4.],
        [ 64.]],

       [[ 49.],
        [121.],
        [100.],
        [  4.],
        [ 25.]]])

In [ ]:
# Transpose the latest array
sq1.T

array([[[ 16., 121.,  49.],
        [ 16.,  64., 121.],
        [100., 100., 100.],
        [ 64.,   4.,   4.],
        [ 36.,  64.,  25.]]])

What does the transpose do?

Transpose (.T),an attribute, reverses the axes of an array.

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
p1 = np.random.randint(0,10, size = (3, 3))
p2 = np.random.randint(0, 10, size=(3, 2))
p1,p2

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 array([[0, 7],
        [2, 2],
        [0, 4]]))

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(p1,p2)

array([[16, 40],
       [14, 70],
       [14, 71]])

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
p3 = np.random.randint(0,10, size = (4, 3))
p4 = np.random.randint(0, 10, size=(4, 3))
p3,p4

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4],
        [1, 4, 7]]),
 array([[9, 8, 8],
        [0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]))

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(p3,p4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

It Doesn't work because the shape of both the arrays are same. It can be fixed by transposing one of the arrays such that their inner dimensions are same.

In [58]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(p3,p4.T), np.dot(p3.T, p4)

(array([[161,  62,  79,  88],
        [131,  92,  73,  82],
        [160,  80, 113, 113],
        [ 97,  74,  36,  49]]),
 array([[152, 159,  92],
        [ 93, 141,  58],
        [162, 197, 122]]))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [61]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
p5 = np.random.randint(0,10, (3,4))
p6 = np.random.randint(0,10, (3,4))
p5,p6

(array([[9, 8, 4, 5],
        [3, 9, 6, 8],
        [6, 0, 0, 8]]),
 array([[8, 3, 8, 2],
        [6, 5, 7, 8],
        [4, 0, 2, 9]]))

In [62]:
# Compare the two arrays with '>'
p5>p6

array([[ True,  True, False,  True],
       [False,  True, False, False],
       [ True, False, False, False]])

What happens when you compare the arrays with `>`?

This compares each corresponding elements of the two arrays and returns True if the element in the first array is greater otherwise returns False.

In [63]:
# Compare the two arrays with '>='
p5 >= p6

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [ True,  True, False, False]])

In [ ]:
# Find which elements of the first array are greater than 7
p5, p5[p5 > 7], np.nonzero(p5>7) # nonzero() displays the indices of elements

(array([[9, 8, 4, 5],
        [3, 9, 6, 8],
        [6, 0, 0, 8]]),
 array([9, 8, 9, 8, 8]),
 (array([0, 0, 1, 1, 2], dtype=int64), array([0, 1, 1, 3, 3], dtype=int64)))

In [79]:
# Which parts of each array are equal? (try using '==')
equals = p5[p5 == p6]
equals

array([8, 0])

In [93]:
# Sort one of the arrays you just created in ascending order
p7 = np.sort(p5, axis = 1) # if axis = 1, it sorts the array row-wise and if axis = 0, it sorts column wise. 
p7

array([[4, 5, 8, 9],
       [3, 6, 8, 9],
       [0, 0, 6, 8]])

In [97]:
# Sort the indexes of one of the arrays you just created
p6, np.argsort(p6)

(array([[8, 3, 8, 2],
        [6, 5, 7, 8],
        [4, 0, 2, 9]]),
 array([[3, 1, 0, 2],
        [1, 0, 2, 3],
        [1, 2, 0, 3]], dtype=int64))

In [100]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(p6), np.max(p6)

(11, 9)

In [101]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(p6)

9

In [102]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(p6, axis=1)

array([0, 3, 3], dtype=int64)

In [104]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(p6, axis=1)

array([3, 1, 1], dtype=int64)

In [106]:
# Create an array of normally distributed random numbers
np.random.randn(3,4)

array([[-0.16606091,  0.21493883, -2.02231493, -0.94305681],
       [ 1.40395874, -0.0185508 , -1.67350462, -1.07253183],
       [-0.99258618,  0.10234768, -0.43260928, -0.6591823 ]])

In [107]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])